"""Broken references and impossible dates across dataset/.

Read-only: writes scoping/integrity_checks.md and touches nothing in dataset/.
"""
import csv
import glob
import os
from datetime import date

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
DATA = os.path.join(ROOT, "dataset")
OUT = os.path.join(ROOT, "scoping", "integrity_checks.md")
TODAY = date(2026, 9, 3)
MAX_EXAMPLES = 5


def load(name):
    with open(os.path.join(DATA, name), newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def parse_date(s):
    s = (s or "").strip()
    if not s:
        return None
    try:
        return date.fromisoformat(s)
    except ValueError:
        return "BAD"


def section(title, rows, fmt, total=None, note=None):
    lines = [f"### {title}", ""]
    if note:
        lines += [note, ""]
    denom = f" of {total}" if total is not None else ""
    lines.append(f"**Count: {len(rows)}{denom}**")
    lines.append("")
    for r in rows[:MAX_EXAMPLES]:
        lines.append(f"- {fmt(r)}")
    if not rows:
        lines.append("- (none)")
    lines.append("")
    return lines


def main():
    requests = load("intro_requests.csv")
    outcomes = load("intro_outcomes.csv")
    roster = load("connector_roster.csv")
    crm = load("crm_accounts.csv")

    md = ["# Integrity checks across `dataset/`", "",
          f"Reference date for \"future\" checks: {TODAY}. Generated by `scoping/integrity_checks.py`; "
          "nothing in `dataset/` was modified. Up to 5 examples per check.", ""]

    # 1. request_id cross-reference
    md += ["## 1. `intro_outcomes.request_id` <-> `intro_requests.request_id`", ""]
    req_ids = {r["request_id"].strip() for r in requests}
    out_ids = {o["request_id"].strip() for o in outcomes}
    orphans = [o for o in outcomes if o["request_id"].strip() not in req_ids]
    md += section("Outcomes whose `request_id` has no matching request", orphans,
                  lambda o: f"`{o['request_id']}` — connector_asked={o['connector_asked']}, asked_date={o['asked_date']}",
                  total=len(outcomes))
    no_outcome = [r for r in requests if r["request_id"].strip() not in out_ids]
    md += section("Requests with no row in `intro_outcomes`", no_outcome,
                  lambda r: f"`{r['request_id']}` — requested_by={r['requested_by']}, status={r['status']}, path_found_flag={r['path_found_flag']}",
                  total=len(requests),
                  note="Expected to be large: an outcome row exists only when a connector was actually asked. "
                       "Breakdown by `status` of the un-matched requests is given below.")
    from collections import Counter
    st = Counter(r["status"] for r in no_outcome)
    md += ["| status | requests without outcome |", "| --- | ---: |"]
    md += [f"| {k} | {v} |" for k, v in st.most_common()]
    md.append("")
    dup_out = Counter(o["request_id"] for o in outcomes)
    dups = [(k, v) for k, v in dup_out.items() if v > 1]
    md += section("`request_id` values appearing more than once in `intro_outcomes`", dups,
                  lambda kv: f"`{kv[0]}` — {kv[1]} rows")

    # 2. connector_asked vs roster
    md += ["## 2. `intro_outcomes.connector_asked` not in `connector_roster.csv`", ""]
    roster_names = {r["name"].strip() for r in roster}
    bad_conn = [o for o in outcomes if o["connector_asked"].strip() not in roster_names]
    by_name = Counter(o["connector_asked"] for o in bad_conn)
    md += section("Rows whose `connector_asked` is not a rostered connector", bad_conn,
                  lambda o: f"`{o['connector_asked']}` — request_id={o['request_id']}, asked_date={o['asked_date']}",
                  total=len(outcomes))
    md += ["Distinct unrostered names: " + ", ".join(f"`{n}` ({c})" for n, c in by_name.most_common()), ""]
    req_by = {r["requested_by"].strip() for r in requests}
    owners = {c["owner"].strip() for c in crm}
    md += ["Where else do these names appear?", ""]
    for n in by_name:
        places = [p for p, s in (("intro_requests.requested_by", req_by), ("crm_accounts.owner", owners)) if n in s]
        md.append(f"- `{n}`: {', '.join(places) if places else 'nowhere else'}")
    md.append("")

    # 3. owner vs requested_by
    md += ["## 3. `crm_accounts.owner` vs `intro_requests.requested_by`", ""]
    only_owner = sorted(owners - req_by)
    only_req = sorted(req_by - owners)
    both = sorted(owners & req_by)
    owner_cnt = Counter(c["owner"].strip() for c in crm)
    req_cnt = Counter(r["requested_by"].strip() for r in requests)
    md += [f"- distinct owners: {len(owners)}; distinct requesters: {len(req_by)}; in both: {len(both)}",
           f"- **Not the same population**: {len(only_owner)} only own accounts, {len(only_req)} only file requests." if only_owner or only_req
           else "- Same population: every owner files requests and vice versa.", ""]
    md += section("Appear only as `crm_accounts.owner` (never request an intro)", only_owner,
                  lambda n: f"`{n}` — owns {owner_cnt[n]} account(s)")
    md += section("Appear only as `intro_requests.requested_by` (own no CRM account)", only_req,
                  lambda n: f"`{n}` — {req_cnt[n]} request(s); roles: {', '.join(sorted({r['requester_role'] for r in requests if r['requested_by'].strip() == n}))}")
    md += ["Full lists:", "",
           "- only owner: " + (", ".join(f"`{n}`" for n in only_owner) or "(none)"),
           "- only requester: " + (", ".join(f"`{n}`" for n in only_req) or "(none)"),
           "- both: " + (", ".join(f"`{n}`" for n in both) or "(none)"), ""]

    # 4. date ordering / future in intro_outcomes
    md += ["## 4. Date ordering in `intro_outcomes`", ""]
    unparse = []
    resp_before = []
    intro_before = []
    future = []
    for o in outcomes:
        d = {k: parse_date(o[k]) for k in ("asked_date", "response_date", "intro_date")}
        for k, v in d.items():
            if v == "BAD":
                unparse.append((o, k))
        d = {k: (v if v != "BAD" else None) for k, v in d.items()}
        if d["asked_date"] and d["response_date"] and d["response_date"] < d["asked_date"]:
            resp_before.append(o)
        if d["response_date"] and d["intro_date"] and d["intro_date"] < d["response_date"]:
            intro_before.append(o)
        for k, v in d.items():
            if v and v > TODAY:
                future.append((o, k, v))
    fmt_o = lambda o: (f"`{o['request_id']}` — {o['connector_asked']}: asked={o['asked_date']}, "
                       f"response={o['response_date'] or '—'}, intro={o['intro_date'] or '—'}")
    md += section("Unparseable date values", unparse, lambda t: f"`{t[0]['request_id']}` — {t[1]}={t[0][t[1]]!r}")
    md += section("`response_date` before `asked_date`", resp_before, fmt_o, total=len(outcomes))
    md += section("`intro_date` before `response_date`", intro_before, fmt_o, total=len(outcomes))
    md += section(f"Any `intro_outcomes` date after {TODAY}", future,
                  lambda t: f"`{t[0]['request_id']}` — {t[1]}={t[2]}", total=len(outcomes))

    # future dates in other tables
    md += ["## 5. Dates after the reference date in other tables", ""]
    fut_req = [(r, parse_date(r["request_date"])) for r in requests]
    fut_req = [(r, d) for r, d in fut_req if d not in (None, "BAD") and d > TODAY]
    md += section(f"`intro_requests.request_date` after {TODAY}", fut_req,
                  lambda t: f"`{t[0]['request_id']}` — {t[1]}", total=len(requests))
    fut_crm = [(c, parse_date(c["last_touch_date"])) for c in crm]
    fut_crm = [(c, d) for c, d in fut_crm if d not in (None, "BAD") and d > TODAY]
    md += section(f"`crm_accounts.last_touch_date` after {TODAY}", fut_crm,
                  lambda t: f"`{t[0]['account_id']}` {t[0]['account_name']} — {t[1]}", total=len(crm))

    md += ["### `connections_*.connected_on` in the future", ""]
    total_conn = 0
    all_fut = []
    bad_conn_dates = []
    rows_tbl = ["| file | rows | future `connected_on` | unparseable |", "| --- | ---: | ---: | ---: |"]
    for path in sorted(glob.glob(os.path.join(DATA, "connections_*.csv"))):
        fname = os.path.basename(path)
        rows = load(fname)
        total_conn += len(rows)
        f_here = []
        b_here = 0
        for r in rows:
            d = parse_date(r["connected_on"])
            if d == "BAD":
                b_here += 1
                bad_conn_dates.append((fname, r))
            elif d and d > TODAY:
                f_here.append((fname, r, d))
        all_fut += f_here
        rows_tbl.append(f"| {fname} | {len(rows)} | {len(f_here)} | {b_here} |")
    md += rows_tbl + [""]
    md += section("Future `connected_on` rows (all files)", all_fut,
                  lambda t: f"{t[0]}: `{t[1]['name']}` @ {t[1]['company']} — {t[2]}", total=total_conn)
    md += section("Unparseable `connected_on` values", bad_conn_dates,
                  lambda t: f"{t[0]}: `{t[1]['name']}` — {t[1]['connected_on']!r}")

    # 6. flag/date consistency
    md += ["## 6. Flag / date consistency in `intro_outcomes`", ""]
    n_resp_date = [o for o in outcomes if o["responded"].strip().upper() == "N" and o["response_date"].strip()]
    y_resp_nodate = [o for o in outcomes if o["responded"].strip().upper() == "Y" and not o["response_date"].strip()]
    n_intro_date = [o for o in outcomes if o["intro_sent"].strip().upper() == "N" and o["intro_date"].strip()]
    y_intro_nodate = [o for o in outcomes if o["intro_sent"].strip().upper() == "Y" and not o["intro_date"].strip()]
    intro_no_resp = [o for o in outcomes if o["intro_sent"].strip().upper() == "Y" and o["responded"].strip().upper() != "Y"]
    fmt_f = lambda o: (f"`{o['request_id']}` — {o['connector_asked']}: responded={o['responded']}, "
                       f"response_date={o['response_date'] or '—'}, intro_sent={o['intro_sent']}, intro_date={o['intro_date'] or '—'}")
    md += section("`responded = N` but `response_date` present", n_resp_date, fmt_f, total=len(outcomes))
    md += section("`intro_sent = N` but `intro_date` present", n_intro_date, fmt_f, total=len(outcomes))
    md += section("(bonus) `responded = Y` with no `response_date`", y_resp_nodate, fmt_f, total=len(outcomes))
    md += section("(bonus) `intro_sent = Y` with no `intro_date`", y_intro_nodate, fmt_f, total=len(outcomes))
    md += section("(bonus) `intro_sent = Y` but `responded != Y`", intro_no_resp, fmt_f, total=len(outcomes))
    flag_vals = Counter((o["responded"], o["intro_sent"], o["meeting_booked"], o["opportunity_created"]) for o in outcomes)
    md += ["Flag value combinations (responded, intro_sent, meeting_booked, opportunity_created):", ""]
    md += [f"- `{'/'.join(k)}`: {v}" for k, v in flag_vals.most_common()]
    md.append("")

    # summary table
    summary = [
        ("outcomes with orphan request_id", len(orphans)),
        ("requests with no outcome row", len(no_outcome)),
        ("duplicate request_id in outcomes", len(dups)),
        ("connector_asked not in roster", len(bad_conn)),
        ("names only in crm_accounts.owner", len(only_owner)),
        ("names only in intro_requests.requested_by", len(only_req)),
        ("response_date < asked_date", len(resp_before)),
        ("intro_date < response_date", len(intro_before)),
        (f"intro_outcomes dates > {TODAY}", len(future)),
        (f"intro_requests.request_date > {TODAY}", len(fut_req)),
        (f"crm_accounts.last_touch_date > {TODAY}", len(fut_crm)),
        ("connections_*.connected_on in future", len(all_fut)),
        ("responded=N with response_date", len(n_resp_date)),
        ("intro_sent=N with intro_date", len(n_intro_date)),
    ]
    head = ["## Summary", "", "| check | count |", "| --- | ---: |"] + [f"| {k} | {v} |" for k, v in summary] + [""]
    md = md[:4] + head + md[4:]

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
